[package]
name = "upload"
version = "0.1.0"
authors = ["abhibhag"]
edition = "2018"

[dependencies]
tokio = {version="0.2.21", features=["macros", "rt-threaded", "fs"]}
warp = "0.2.5"
uuid = {version="0.8", features=["v4"]}
futures = {version = "0.3.5", default-features=false}
bytes = "0.5.6"